
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.70.0.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.WorldRenderer.LIB.Proto;
using XTC.FMP.MOD.WorldRenderer.LIB.Bridge;

namespace XTC.FMP.MOD.WorldRenderer.LIB.MVCS
{

    public class HealthyEchoRequestDTO : IDTO
    {
        public HealthyEchoRequestDTO(HealthyEchoRequest _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoRequest Value;
    }



    public class HealthyEchoResponseDTO : IDTO
    {
        public HealthyEchoResponseDTO(HealthyEchoResponse _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoResponse Value;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _value)
        {
            Value = _value;    
        }
        public readonly Status Value;
    }



    public class BlankRequestDTO : IDTO
    {
        public BlankRequestDTO(BlankRequest _value)
        {
            Value = _value;    
        }
        public readonly BlankRequest Value;
    }



    public class BlankResponseDTO : IDTO
    {
        public BlankResponseDTO(BlankResponse _value)
        {
            Value = _value;    
        }
        public readonly BlankResponse Value;
    }



    public class ScopeRequestDTO : IDTO
    {
        public ScopeRequestDTO(ScopeRequest _value)
        {
            Value = _value;    
        }
        public readonly ScopeRequest Value;
    }



    public class ScopeResponseDTO : IDTO
    {
        public ScopeResponseDTO(ScopeResponse _value)
        {
            Value = _value;    
        }
        public readonly ScopeResponse Value;
    }



    public class UuidRequestDTO : IDTO
    {
        public UuidRequestDTO(UuidRequest _value)
        {
            Value = _value;    
        }
        public readonly UuidRequest Value;
    }



    public class UuidResponseDTO : IDTO
    {
        public UuidResponseDTO(UuidResponse _value)
        {
            Value = _value;    
        }
        public readonly UuidResponse Value;
    }



}
